name: Testing 

on:
  push:
    branches: [ "patch/dev/brando-updatingLibsAndTesting" ]

jobs:
  job1:
    name: Modifiy repository files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        token: ${{ secrets.PAT_TOKEN }}
    - name: Modifiy the specific files using scripts
      run: |
        echo "hello world";

